var express = require('express');
var router = express.Router();
const onBoardingRouter = require('../app/v1/onBoarding/router');
const blogRouter = require('../app/v1/blog/router');
const userRouter = require('../app/v1/user/router');
const categoriesRouter = require('../app/v1/categories/router');
const imagesRouter = require('../app/v1/images/router');
const videosRouter = require('../app/v1/videos/router');
const eventsRouter = require('../app/v1/events/router');
const newsRouter = require('../app/v1/news/router');
const schemesRouter = require('../app/v1/schemes/router');
const donationsRouter = require('../app/v1/donations/router');
const villageRouter = require('../app/v1/village/router');
const contactsRouter = require('../app/v1/contacts/router');
const notificationsRouter = require('../app/v1/notifications/router');
const searchRouter = require('../app/v1/search/router');
const adminRouter = require('../app/v1/admin/router');
const commentsRouter = require('../app/v1/comments/router');
const likesRouter = require('../app/v1/likes/router');
const bookmarksRouter = require('../app/v1/bookmarks/router');
const profileRouter = require('../app/v1/profile/router');

router.use('/onBoarding', onBoardingRouter);
router.use('/blog', blogRouter);
router.use('/users', userRouter);
router.use('/categories', categoriesRouter);
router.use('/images', imagesRouter);
router.use('/videos', videosRouter);
router.use('/events', eventsRouter);
router.use('/news', newsRouter);
router.use('/schemes', schemesRouter);
router.use('/donations', donationsRouter);
router.use('/village', villageRouter);
router.use('/contacts', contactsRouter);
router.use('/notifications', notificationsRouter);
router.use('/search', searchRouter);
router.use('/admin', adminRouter);
router.use('/comments', commentsRouter);
router.use('/likes', likesRouter);
router.use('/bookmarks', bookmarksRouter);
router.use('/profile', profileRouter);

module.exports = router;
