var express = require('express');
var router = express.Router();
const onBoardingRouter = require('../app/v1/onBoarding/router');
const blogRouter = require('../app/v1/blog/router');
const userRouter = require('../app/v1/user/router');
const categoriesRouter = require('../app/v1/categories/router');
const imagesRouter = require('../app/v1/images/router');
const videosRouter = require('../app/v1/videos/router');
const eventsRouter = require('../app/v1/events/router');
const newsRouter = require('../app/v1/news/router');
const schemesRouter = require('../app/v1/schemes/router');
const donationsRouter = require('../app/v1/donations/router');
const villageRouter = require('../app/v1/village/router');
const contactsRouter = require('../app/v1/contacts/router');
const notificationsRouter = require('../app/v1/notifications/router');
const searchRouter = require('../app/v1/search/router');
const adminRouter = require('../app/v1/admin/router');
const commentsRouter = require('../app/v1/comments/router');
const likesRouter = require('../app/v1/likes/router');
const bookmarksRouter = require('../app/v1/bookmarks/router');
const profileRouter = require('../app/v1/profile/router');
const investorsRouter = require('../app/v1/investors/router');
const complaintsRouter = require('../app/v1/complaints/router');
const suggestionsRouter = require('../app/v1/suggestions/router');
const newslettersRouter = require('../app/v1/newsletters/router');
const workersRouter = require('../app/v1/workers/router');
const workerRequestsRouter = require('../app/v1/worker-requests/router');
const workerReviewsRouter = require('../app/v1/worker-reviews/router');
const emergencyContactsRouter = require('../app/v1/emergency-contacts/router');
const localServicesRouter = require('../app/v1/local-services/router');
const agricultureServicesRouter = require('../app/v1/agriculture-services/router');
const jobsRouter = require('../app/v1/jobs/router');
const marketplaceRouter = require('../app/v1/marketplace/router');

const departmentsRouter = require('../app/v1/departments/router');
const rolesRouter = require('../app/v1/roles/router');
const govUsersRouter = require('../app/v1/gov-users/router');
const projectsRouter = require('../app/v1/projects/router');
const documentsRouter = require('../app/v1/documents/router');
const fundsRouter = require('../app/v1/funds/router');
const auditRouter = require('../app/v1/audit/router');
const tasksRouter = require('../app/v1/tasks/router');
const meetingsRouter = require('../app/v1/meetings/router');
const analyticsRouter = require('../app/v1/analytics/router');
const residentsRouter = require('../app/v1/residents/router');

router.use('/onBoarding', onBoardingRouter);
router.use('/blog', blogRouter);
router.use('/users', userRouter);
router.use('/categories', categoriesRouter);
router.use('/images', imagesRouter);
router.use('/videos', videosRouter);
router.use('/events', eventsRouter);
router.use('/news', newsRouter);
router.use('/schemes', schemesRouter);
router.use('/donations', donationsRouter);
router.use('/village', villageRouter);
router.use('/contacts', contactsRouter);
router.use('/notifications', notificationsRouter);
router.use('/search', searchRouter);
router.use('/admin', adminRouter);
router.use('/comments', commentsRouter);
router.use('/likes', likesRouter);
router.use('/bookmarks', bookmarksRouter);
router.use('/profile', profileRouter);
router.use('/investors', investorsRouter);
router.use('/complaints', complaintsRouter);
router.use('/suggestions', suggestionsRouter);
router.use('/newsletters', newslettersRouter);
router.use('/workers', workersRouter);
router.use('/worker-requests', workerRequestsRouter);
router.use('/worker-reviews', workerReviewsRouter);
router.use('/emergency-contacts', emergencyContactsRouter);
router.use('/local-services', localServicesRouter);
router.use('/agriculture-services', agricultureServicesRouter);
router.use('/jobs', jobsRouter);
router.use('/marketplace', marketplaceRouter);

router.use('/departments', departmentsRouter);
router.use('/roles', rolesRouter);
router.use('/gov-users', govUsersRouter);
router.use('/projects', projectsRouter);
router.use('/documents', documentsRouter);
router.use('/funds', fundsRouter);
router.use('/audit', auditRouter);
router.use('/tasks', tasksRouter);
router.use('/meetings', meetingsRouter);
router.use('/analytics', analyticsRouter);
router.use('/residents', residentsRouter);

module.exports = router;
